# Generated by Django 3.2.15 on 2022-08-27 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_comment_posts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='approve',
            new_name='approved',
        ),
    ]
